<?php
session_start();

require('../HpDashboard/BloodInventory/fpdf/fpdf.php');

// Check if the required session variables are set
if (!isset($_SESSION['cardNumber'], $_SESSION['firstName'], $_SESSION['lastName'], $_SESSION['bloodType'], $_SESSION['address'], $_SESSION['donorNIC'], $_SESSION['issuedDate'], $_SESSION['profilePicture'])) {
    echo "Required donor details are missing.";
    exit;
}

class PDF extends FPDF
{
    // Header of the document
    function Header()
    {
        $this->SetFont('Arial', 'B', 16);
        $this->Cell(0, 10, 'BloodLinePro Donor ID Card', 0, 1, 'C');
        $this->Ln(10);
    }

    // Footer of the document
    function Footer()
    {
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 8);
        $this->Cell(0, 10, 'Generated by BloodLinePro', 0, 0, 'C');
    }

    // Create Donor Card Content
    function DonorCard($donorDetails)
    {
        $this->SetFont('Arial', '', 12);

        // Profile Picture (if exists)
        if (!empty($donorDetails['profilePicture']) && file_exists($donorDetails['profilePicture'])) {
            $this->Image($donorDetails['profilePicture'], 10, 20, 30); // Adjust position and size as needed
        }

        // Donor Information
        $this->Ln(40); // Adjust the position below the image
        $this->Cell(40, 10, 'Name: ' . $donorDetails['firstName'] . ' ' . $donorDetails['lastName']);
        $this->Ln(10);
        $this->Cell(40, 10, 'NIC: ' . $donorDetails['donorNIC']);
        $this->Ln(10);
        $this->Cell(40, 10, 'Blood Type: ' . $donorDetails['bloodType']);
        $this->Ln(10);
        $this->Cell(40, 10, 'Address: ' . $donorDetails['address']);
        $this->Ln(10);
        $this->Cell(40, 10, 'Issued Date: ' . $donorDetails['issuedDate']);
        $this->Ln(10);
        $this->Cell(40, 10, 'Card Number: ' . $donorDetails['cardNumber']);
        $this->Ln(20);
        $this->Cell(40, 10, 'Signature: HP/MHO/SHO');
    }
}

// Create a new PDF instance
$pdf = new PDF();
$pdf->AddPage();

// Donor details from the session
$donorDetails = [
    'firstName' => $_SESSION['firstName'],
    'lastName' => $_SESSION['lastName'],
    'donorNIC' => $_SESSION['donorNIC'],
    'bloodType' => $_SESSION['bloodType'],
    'address' => $_SESSION['address'],
    'issuedDate' => $_SESSION['issuedDate'],
    'cardNumber' => $_SESSION['cardNumber'],
    'profilePicture' => $_SESSION['profilePicture'] // Ensure this path is valid
];

// Generate the Donor Card
$pdf->DonorCard($donorDetails);

// Output the PDF (download it)
$pdf->Output('D', 'donor_card.pdf');
?>
